// Vercel serverless function entry point.
// api/handler.mjs is generated by `npm run build:vercel` inside the app/ directory.

let _app = null;

async function getApp() {
  if (!_app) {
    const mod = await import('./handler.mjs');
    _app = mod.default;
  }
  return _app;
}

module.exports = async function handler(req, res) {
  const app = await getApp();

  const proto = (req.headers['x-forwarded-proto'] || 'https').split(',')[0].trim();
  const host = req.headers['x-forwarded-host'] || req.headers.host || 'localhost';
  const url = new URL(req.url, `${proto}://${host}`);

  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value !== undefined && value !== null) {
      headers.set(key, Array.isArray(value) ? value.join(', ') : String(value));
    }
  }

  let body = null;
  if (req.method !== 'GET' && req.method !== 'HEAD') {
    const chunks = [];
    for await (const chunk of req) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    }
    if (chunks.length > 0) body = Buffer.concat(chunks);
  }

  const request = new Request(url.toString(), {
    method: req.method,
    headers,
    body,
  });

  let response;
  try {
    response = await app.fetch(request);
  } catch (err) {
    console.error('API handler error:', err);
    res.status(500).json({ error: 'Internal Server Error' });
    return;
  }

  res.status(response.status);
  response.headers.forEach((value, key) => {
    const skip = ['content-encoding', 'transfer-encoding', 'connection', 'keep-alive'];
    if (!skip.includes(key.toLowerCase())) {
      res.setHeader(key, value);
    }
  });

  const buffer = Buffer.from(await response.arrayBuffer());
  res.end(buffer);
};

module.exports.config = {
  api: {
    bodyParser: false,
    externalResolver: true,
  },
};
